# switch:
#   - platform: shelly
#     switches:
#       shelly_switch:
#         # path: /relay/0
#         host: 10.7.0.101
#         username: !secret shelly_username
#         password: !secret shelly_password


switch:
  - platform: rest
    name: "Shelly: Bathroom Ceiling"
    resource: !secret shelly_bathroom_ceiling_resource
    method: post
    scan_interval: 3
    body_on: 'turn=on'
    body_off: 'turn=off'
    is_on_template: '{{ value_json.ison == true }}'
    username: !secret shelly_bathroom_ceiling_username
    password: !secret shelly_bathroom_ceiling_password
    headers:
      Content-Type: application/x-www-form-urlencoded

  - platform: rest
    name: "Shelly: Project Nothing"
    resource: !secret shelly_project_nothing_resource
    method: post
    scan_interval: 3
    body_on: 'turn=on'
    body_off: 'turn=off'
    is_on_template: '{{ value_json.ison == true }}'
    username: !secret shelly_project_nothing_username
    password: !secret shelly_project_nothing_password
    headers:
      Content-Type: application/x-www-form-urlencoded


light:
  - platform: template
    lights:
      bathroom_ceiling:
        friendly_name: "Bathroom Ceiling Light"
        value_template: "{{ is_state('switch.shelly_bathroom_ceiling', 'on') }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.shelly_bathroom_ceiling
        turn_off:
          service: switch.turn_off
          entity_id: switch.shelly_bathroom_ceiling


automation:
  - alias: Sync state of bathroom ceiling light with bathroom light (ON)
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.bathroom_light
        to: 'on'
    action:
      service: light.turn_on
      entity_id: light.bathroom_ceiling

  - alias: Sync state of bathroom ceiling light with bathroom light (OFF)
    initial_state: true
    trigger:
      - platform: state
        entity_id: light.bathroom_light
        to: 'off'
    action:
      service: light.turn_off
      entity_id: light.bathroom_ceiling


  - alias: "DEBUG: Shelly p0 notify when status changes"
    initial_state: true
    trigger:
      - platform: state
        entity_id: switch.shelly_project_nothing
    action:
      - service: notify.html5
        data_template:
          message: "Shelly project nothing: {{ trigger.to_state.state }}"
          data:
            tag: "shelly-project-nothing"

# vim: set filetype=yaml et sw=2 ts=2 :
