tts:
  - platform: google
    cache_dir: /tmp/tts.cache
    time_memory: 900
    language: 'fr'

  - platform: voicerss
    api_key: !secret voicerss_api_key
    language: 'fr-fr'
    codec: mp3
    format: 8khz_8bit_mono


script:
  reset_tts_volume:
    sequence:
      - service: media_player.volume_mute
        data:
          entity_id: media_player.office_speaker
          is_volume_muted: False
      - service: media_player.volume_set
        data:
          entity_id: media_player.office_speaker
          volume_level: 0.4
      - service: media_player.volume_mute
        data:
          entity_id: media_player.living_room_speaker
          is_volume_muted: False
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_speaker
          volume_level: 0.4

  tts_say:
    sequence:
      - service: script.reset_tts_volume
      - service: tts.google_say
        data_template:
          entity_id: media_player.cast_home_group
          message: '{{ message }}'
          language: '{{ language|default("fr") }}'
      - service: automation.turn_on
        entity_id: automation.switch_back_to_aux_in_when_tts_message_has_finished_playing

  zanzito_tts_say:
    sequence:
      - condition: state
        entity_id: input_boolean.dnd
        state: 'off'
      - service: notify.zanzito_tts
        data_template:
          message: "{{ message }}"

# vim: set filetype=yaml et sw=2 ts=2 :
